apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: queue-job-consumer
  namespace: default
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: queue-job-consumer
        annotations:
          karpenter.sh/do-not-disrupt: "true"
      spec:        
        nodeSelector:
          intent: scaling-tests
          karpenter.sh/capacity-type: on-demand
        tolerations:
        - key: scaling-tests
          operator: Exists
        containers:
        - name: consumer
          image: christianhxc/rabbitmq-consumer:latest
          imagePullPolicy: Always
          env:
          - name: RABBITMQ_URL
            value: "amqp://user:autoscaling@rabbitmq.default.svc.cluster.local:5672"
          - name: QUEUE_NAME
            value: "autoscaling"
          - name: BATCH_SIZE
            value: "1"
          resources:
            requests:
              cpu: 350m
              memory: 128Mi
        topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: queue-job-consumer
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
  pollingInterval: 5   # Check every 5 seconds
  maxReplicaCount: 30  # Maximum number of replicas
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  triggers:
  - type: rabbitmq
    metadata:
      queueName: autoscaling
      mode: QueueLength
      value: "5"
    authenticationRef:
      name: rabbitmq-auth
---
apiVersion: batch/v1
kind: Job
metadata:
  name: very-important-job
spec:
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      annotations:
        karpenter.sh/do-not-disrupt: "true"
    spec:
      nodeSelector:
        intent: scaling-tests
        karpenter.sh/capacity-type: on-demand
      tolerations:
        - key: scaling-tests
          operator: Exists
      containers:
      - name: very-important-job
        image: alpine
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 7
        command: ['sh', '-c', 'echo A very important Job is running ; sleep 60']
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
  backoffLimit: 2