apiVersion: v1
kind: ConfigMap
metadata:
  name: montecarlo-pi-load-test-script
data:
  incremental_load_test.sh: |
    #!/bin/bash

    URL="http://montecarlo-pi/monte-carlo-pi?iterations=10000000"
    DURATION=180  # 3 minutes in seconds
    INTERVAL=10   # Increase load every 10 seconds
    START_CONCURRENCY=1
    MAX_CONCURRENCY=50

    current_time=0
    concurrency=$START_CONCURRENCY

    while [ $current_time -lt $DURATION ]; do
        ab -n 100 -c $concurrency -t 10 $URL &
        
        echo "Running test with concurrency: $concurrency"
        
        sleep $INTERVAL
        current_time=$((current_time + INTERVAL))
        concurrency=$((concurrency + 1))
        
        if [ $concurrency -gt $MAX_CONCURRENCY ]; then
            concurrency=$MAX_CONCURRENCY
        fi
    done

    wait  # Wait for all background processes to finish

    echo "Load test completed"