apiVersion: apps/v1
kind: Deployment
metadata:
  name: montecarlo-pi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: montecarlo-pi
  template:
    metadata:
      labels:
        app: montecarlo-pi
    spec:
      containers:
      - name: montecarlo-pi
        image: christianhxc/montecarlo-pi
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 900m
            memory: 512Mi
          limits:
            cpu: 1200m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: montecarlo-pi
  labels:
    app: montecarlo-pi
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: montecarlo-pi
