apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: montecarlo-pi-latency
spec:
  scaleTargetRef:
    name: montecarlo-pi
  minReplicaCount: 1
  maxReplicaCount: 10
  advanced:
    horizontalPodAutoscalerConfig: 
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Percent
            value: 100
            periodSeconds: 5
        scaleDown:
          stabilizationWindowSeconds: 120
          policies:
          - type: Percent
            value: 100
            periodSeconds: 30
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
      metricName: http_requests_total
      threshold: "10" # Scale out if total request rate across all pods exceeds 10 rps
      query: |
        sum(rate(http_requests_total{namespace="default",pod=~"montecarlo-pi-.*"}[1m]))