apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: montecarlo-pi-latency
spec:
  scaleTargetRef:
    name: montecarlo-pi
  minReplicaCount: 1
  maxReplicaCount: 10
  advanced:
    horizontalPodAutoscalerConfig: 
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Percent
            value: 100
            periodSeconds: 5
        scaleDown:
          stabilizationWindowSeconds: 120
          policies:
          - type: Percent
            value: 100
            periodSeconds: 30
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
      metricName: monte_carlo_latency_seconds
      threshold: "0.4" # assume SLA is 0.8 or 800ms really, but we want to scale out before
      query: |
        sum(histogram_quantile(0.95, rate(monte_carlo_latency_seconds_bucket{namespace="default",pod=~"montecarlo-pi-.*"}[2m])))