prometheus:
  operator:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus
  metricServer:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus
  webhooks:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus