apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: gpu-inference-load-test
spec:
  quiet: "false"
  cleanup: post
  parallelism: 1
  script:
    localFile: /scripts/k6-load-test.js
  runner:
    image: christianhxc/k6-gpu-test:latest
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        memory: "512Mi"
