kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: montecarlopi-http
spec:
    hosts:
        - yourhostname.com
    pathPrefixes:
        - /test
    scaledownPeriod: 300
    scalingMetric:
        concurrency:
            targetValue: 200
        # requestRate:
        #     granularity: 1s
        #     targetValue: 100
        #     window: 1m
    scaleTargetRef:
        name: montecarlo-pi
        kind: Deployment
        apiVersion: apps/v1
        service: montecarlo-pi
        port: 80
    replicas:
        min: 0
        max: 10